/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package startup;

import startup.tableClasses.EntregaTableModel;
import startup.tableClasses.ProdutoTableModel;
import startup.tableClasses.EntregaRealizadaTableModel;
import startup.tableClasses.ClienteTableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author firmi
 */
public class Home extends javax.swing.JFrame {

    public ArrayList<Cliente> clientes = new ArrayList<>();
    public ArrayList<Produto> produtos = new ArrayList<>();
    public ArrayList<Entrega> entregas = new ArrayList<>();
    public ArrayList<EntregaR> entregasRealizadas = new ArrayList<>();
    public Padaria padaria;
    public int cont=0;//para os id´s
    public int contProduto=0;
    public int contEntrega=0;
    public int contEntregaRealizada=0;
    public int id;//selecionar na tabela
    public int idProduto;
    public int idEntrega;
    public int idEntregaRealizada;
    
        
    /**
     * Creates new form Home
     */
    public Home() {
        
        initComponents();
                
        padaria = new Padaria("Pão de queijo", 2.3, 4.5);
        
        limparDadosNaTabela(1);
        limparDadosNaTabela(2);
        
        
    }
    
    
    private void limparDadosNaTabela(int tipoTabela){
        if (tipoTabela == 1){
            jcClientes.removeAllItems();
            for(int i=0; i<clientes.size(); i++){
                jcClientes.addItem(clientes.get(i).getNome());
            }
        } else {
            jcProdutos.removeAllItems();
            for(int i=0; i<produtos.size(); i++){
            jcProdutos.addItem(produtos.get(i).getNome());
        }
        }
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btExcluirCliente = new javax.swing.JButton();
        btExcluirProduto = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jtNomeCliente = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jtBairro = new javax.swing.JTextField();
        jtLatitude = new javax.swing.JTextField();
        jtLongitude = new javax.swing.JTextField();
        jCVip = new javax.swing.JCheckBox();
        btCadastrarCliente = new javax.swing.JButton();
        jtRua = new javax.swing.JTextField();
        jtNumero = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jtNomeProduto = new javax.swing.JTextField();
        jtQtdProduto = new javax.swing.JTextField();
        jtPrecoProduto = new javax.swing.JTextField();
        btCadastrarProduto = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btCadastrarEntrega = new javax.swing.JButton();
        jcProdutos = new javax.swing.JComboBox();
        jcClientes = new javax.swing.JComboBox();
        jtBrinde = new javax.swing.JTextField();
        btCarregarDados = new javax.swing.JButton();
        btSelecionar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaEntregas = new javax.swing.JTable();
        btMarcarEntrega = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaEntregasRealizadas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(63, 19, 10));

        jTabbedPane1.setBackground(new java.awt.Color(0, 255, 0));

        jPanel2.setBackground(new java.awt.Color(114, 29, 7));
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 22767));

        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Endereço", "N°", "Bairro", "Latitude", "Longitude", "VIP"
            }
        ));
        tabelaClientes.setOpaque(false);
        tabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaClientes);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clientes");

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Preco", "Quantidade"
            }
        ));
        tabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaProdutos);
        if (tabelaProdutos.getColumnModel().getColumnCount() > 0) {
            tabelaProdutos.getColumnModel().getColumn(0).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Produtos");

        btExcluirCliente.setForeground(new java.awt.Color(255, 255, 255));
        btExcluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/startup/icons/del.png"))); // NOI18N
        btExcluirCliente.setText("Excluir Cliente");
        btExcluirCliente.setContentAreaFilled(false);
        btExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirClienteActionPerformed(evt);
            }
        });

        btExcluirProduto.setForeground(new java.awt.Color(255, 255, 255));
        btExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/startup/icons/del.png"))); // NOI18N
        btExcluirProduto.setText("Excluir Produto");
        btExcluirProduto.setContentAreaFilled(false);
        btExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(btExcluirProduto))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(219, 219, 219)
                                .addComponent(btExcluirCliente))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                                .addComponent(jScrollPane3)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(btExcluirCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluirProduto))
        );

        jTabbedPane1.addTab("Listar", jPanel2);

        jPanel3.setBackground(new java.awt.Color(114, 29, 7));

        jPanel4.setBackground(new java.awt.Color(166, 54, 9));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jtNomeCliente.setBackground(new java.awt.Color(166, 54, 9));
        jtNomeCliente.setForeground(new java.awt.Color(240, 227, 177));
        jtNomeCliente.setText("Nome do cliente");
        jtNomeCliente.setBorder(null);
        jtNomeCliente.setOpaque(false);
        jtNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeClienteActionPerformed(evt);
            }
        });

        jtBairro.setBackground(new java.awt.Color(166, 54, 9));
        jtBairro.setForeground(new java.awt.Color(240, 227, 177));
        jtBairro.setText("Bairro");
        jtBairro.setOpaque(false);
        jtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBairroActionPerformed(evt);
            }
        });

        jtLatitude.setForeground(new java.awt.Color(240, 227, 177));
        jtLatitude.setText("3.4");
        jtLatitude.setOpaque(false);
        jtLatitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtLatitudeActionPerformed(evt);
            }
        });

        jtLongitude.setForeground(new java.awt.Color(240, 227, 177));
        jtLongitude.setText("5.6");
        jtLongitude.setOpaque(false);

        jCVip.setForeground(new java.awt.Color(255, 255, 255));
        jCVip.setText("VIP");
        jCVip.setOpaque(false);

        btCadastrarCliente.setBackground(new java.awt.Color(204, 204, 0));
        btCadastrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/startup/icons/add.png"))); // NOI18N
        btCadastrarCliente.setText("CADASTRAR");
        btCadastrarCliente.setContentAreaFilled(false);
        btCadastrarCliente.setFocusPainted(false);
        btCadastrarCliente.setOpaque(false);
        btCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarClienteActionPerformed(evt);
            }
        });

        jtRua.setForeground(new java.awt.Color(255, 255, 255));
        jtRua.setText("Rua");
        jtRua.setOpaque(false);

        jtNumero.setForeground(new java.awt.Color(255, 255, 255));
        jtNumero.setText("3");
        jtNumero.setOpaque(false);
        jtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(287, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btCadastrarCliente)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCVip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jtNumero)
                                .addGap(32, 32, 32))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCVip))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btCadastrarCliente)
                .addGap(47, 47, 47))
        );

        jTabbedPane2.addTab("Cliente", jPanel4);

        jPanel5.setBackground(new java.awt.Color(166, 54, 9));

        jtNomeProduto.setForeground(new java.awt.Color(255, 255, 255));
        jtNomeProduto.setText("Nome do produto");
        jtNomeProduto.setOpaque(false);
        jtNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeProdutoActionPerformed(evt);
            }
        });

        jtQtdProduto.setForeground(new java.awt.Color(255, 255, 255));
        jtQtdProduto.setText("Quantidade");
        jtQtdProduto.setOpaque(false);

        jtPrecoProduto.setForeground(new java.awt.Color(255, 255, 255));
        jtPrecoProduto.setText("Preco");
        jtPrecoProduto.setOpaque(false);

        btCadastrarProduto.setForeground(new java.awt.Color(255, 255, 255));
        btCadastrarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/startup/icons/add.png"))); // NOI18N
        btCadastrarProduto.setText("CADASTRAR");
        btCadastrarProduto.setContentAreaFilled(false);
        btCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btCadastrarProduto)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtQtdProduto)
                        .addComponent(jtNomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addComponent(jtPrecoProduto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btCadastrarProduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Produto", jPanel5);

        jPanel6.setBackground(new java.awt.Color(166, 54, 9));

        btCadastrarEntrega.setForeground(new java.awt.Color(255, 255, 255));
        btCadastrarEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/startup/icons/add.png"))); // NOI18N
        btCadastrarEntrega.setText("CADASTRAR");
        btCadastrarEntrega.setContentAreaFilled(false);
        btCadastrarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarEntregaActionPerformed(evt);
            }
        });

        jcProdutos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcClientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jtBrinde.setEditable(false);
        jtBrinde.setText("Não tem brinde");
        jtBrinde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBrindeActionPerformed(evt);
            }
        });

        btCarregarDados.setForeground(new java.awt.Color(255, 255, 255));
        btCarregarDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/startup/icons/load.png"))); // NOI18N
        btCarregarDados.setText("ATUALIZAR");
        btCarregarDados.setContentAreaFilled(false);
        btCarregarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarregarDadosActionPerformed(evt);
            }
        });

        btSelecionar.setText("Tem Brinde?");
        btSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtBrinde, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(278, 278, 278)
                                .addComponent(btSelecionar))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(btCarregarDados))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(btCadastrarEntrega)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCarregarDados)
                .addGap(18, 18, 18)
                .addComponent(jcClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btSelecionar)
                .addGap(28, 28, 28)
                .addComponent(jtBrinde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCadastrarEntrega)
                .addGap(29, 29, 29))
        );

        jTabbedPane2.addTab("Entregas", jPanel6);

        tabelaEntregas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaEntregas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaEntregasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelaEntregas);

        btMarcarEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/startup/icons/despachar.png"))); // NOI18N
        btMarcarEntrega.setText("DESPACHAR");
        btMarcarEntrega.setContentAreaFilled(false);
        btMarcarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMarcarEntregaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btMarcarEntrega)
                .addGap(286, 286, 286))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btMarcarEntrega)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Embaldo", jPanel8);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar", jPanel3);

        jPanel7.setBackground(new java.awt.Color(114, 29, 7));

        tabelaEntregasRealizadas.setBackground(new java.awt.Color(166, 54, 9));
        tabelaEntregasRealizadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaEntregasRealizadas.setOpaque(false);
        jScrollPane2.setViewportView(tabelaEntregasRealizadas);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Painel de entregas", jPanel7);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/startup/icons/bg.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void criarTabelaCliente(){
        ClienteTableModel modelCliente = new ClienteTableModel(clientes);
        tabelaClientes.setModel(modelCliente);
    }
    
    private void jtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeProdutoActionPerformed

    private void btCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarClienteActionPerformed
        // TODO add your handling code here:
        
        Cliente c = new Cliente(cont, jtNomeCliente.getText().toString(), Integer.parseInt(jtNumero.getText().toString()), jtBairro.getText().toString(), Double.parseDouble(jtLatitude.getText().toString()), Double.parseDouble(jtLongitude.getText().toString()), jCVip.isSelected());
        clientes.add(c);
        
        criarTabelaCliente();
        
        cont++;
        
        JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
        
    }//GEN-LAST:event_btCadastrarClienteActionPerformed

    private void jtLatitudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtLatitudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtLatitudeActionPerformed

    private void jtNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeClienteActionPerformed

    private void jtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBairroActionPerformed

    private void jtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNumeroActionPerformed

    private void btExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirClienteActionPerformed
        // TODO add your handling code here:
        
        for(int i=0; i<clientes.size(); i++){
            if(clientes.get(i).getId() == id){
                clientes.remove(i);
            }
        }
        
        criarTabelaCliente();        
    }//GEN-LAST:event_btExcluirClienteActionPerformed

    private void tabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClientesMouseClicked
        // TODO add your handling code here:
        
        int indiceLinha = tabelaClientes.getSelectedRow();
        id = Integer.parseInt(tabelaClientes.getValueAt(indiceLinha, 0).toString());
        
    }//GEN-LAST:event_tabelaClientesMouseClicked

    private void btCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarProdutoActionPerformed
        // TODO add your handling code here:
        
        if(jtNomeProduto.getText().toString().equals("") || jtPrecoProduto.getText().toString().equals("") || jtQtdProduto.getText().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        } else{
            
            Produto p = new Produto(contProduto, jtNomeProduto.getText().toString(), Integer.parseInt(jtQtdProduto.getText().toString()), Double.parseDouble(jtPrecoProduto.getText().toString()));
            produtos.add(p);

            ProdutoTableModel modelProduto = new ProdutoTableModel(produtos);
            tabelaProdutos.setModel(modelProduto);

            contProduto++;

            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");

        }
        
        
    }//GEN-LAST:event_btCadastrarProdutoActionPerformed

    private void tabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutosMouseClicked
        // TODO add your handling code here:
        
        int indiceLinha = tabelaProdutos.getSelectedRow();
        idProduto = Integer.parseInt(tabelaProdutos.getValueAt(indiceLinha, 0).toString());
        
    }//GEN-LAST:event_tabelaProdutosMouseClicked

    private void btExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirProdutoActionPerformed
        // TODO add your handling code here:
        
        for(int i=0; i<produtos.size(); i++){
            if(produtos.get(i).getId() == idProduto){
                produtos.remove(i);
            }
        }
        
        ProdutoTableModel modelProduto = new ProdutoTableModel(produtos);
        tabelaProdutos.setModel(modelProduto);
        
        
    }//GEN-LAST:event_btExcluirProdutoActionPerformed

    private void btCadastrarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarEntregaActionPerformed
        // TODO add your handling code here:
        
        Cliente c = null;
        
        for(int i=0; i<clientes.size(); i++){
            if(jcClientes.getSelectedItem().toString().equals(clientes.get(i).getNome().toString())){
                c = new Cliente(clientes.get(i).getId(), clientes.get(i).getNome(), clientes.get(i).getNumero(), clientes.get(i).getBairro(), clientes.get(i).getLatitude_cliente(), clientes.get(i).getLongitude_cliente(), clientes.get(i).isVip());
            }
        }
        
        Produto p = null;
        
        for(int i=0; i<produtos.size(); i++){
            if(jcProdutos.getSelectedItem().toString().equals(produtos.get(i).getNome().toString())){
                p = new Produto(produtos.get(i).getId(), produtos.get(i).getNome(), produtos.get(i).getQuantidade(), produtos.get(i).getPrice());
            }
        }
        
        int id = idEntrega;
        String brinde = jtBrinde.getText().toString();
        
        Entrega e = new Entrega(contEntrega, c.getId(), c.getNumero(), c.getNome(), c.getBairro(), c.getLatitude_cliente(), c.getLongitude_cliente(), c.isVip(), p.getId(), p.getNome(), p.getQuantidade(), p.getPrice(), brinde);
        entregas.add(e);
        
        EntregaTableModel modelEntrega = new EntregaTableModel(entregas);
        tabelaEntregas.setModel(modelEntrega);
        
        contEntrega++;
        
        JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
        
    }//GEN-LAST:event_btCadastrarEntregaActionPerformed

    private void jtBrindeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBrindeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBrindeActionPerformed

    private void btCarregarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarregarDadosActionPerformed
        // TODO add your handling code here:
        
        limparDadosNaTabela(1);
        limparDadosNaTabela(2);
        
    }//GEN-LAST:event_btCarregarDadosActionPerformed

    private void tabelaEntregasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaEntregasMouseClicked
        // TODO add your handling code here:
        
        int indiceLinha = tabelaEntregas.getSelectedRow();
        idEntrega = Integer.parseInt(tabelaEntregas.getValueAt(indiceLinha, 0).toString());
        
    }//GEN-LAST:event_tabelaEntregasMouseClicked

    private void btMarcarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMarcarEntregaActionPerformed
        // TODO add your handling code here:

        int idCli=0;
        int numCli=0;
        String nomeCli=null;
        String bairroCli=null;
        double longi=0;
        double lat=0;
        boolean vip=true;
        int idProd=0;
        String nomeProd=null;
        int qtdProd=0;
        double precoProd=0;
        String brinde=null;
        
        for(int i=0; i<entregas.size(); i++){
            if(idEntrega == entregas.get(i).getId()){
                idCli = entregas.get(i).getIdCliente();
                numCli = entregas.get(i).getNumeroCliente();
                nomeCli = entregas.get(i).getNomeCliente();
                bairroCli = entregas.get(i).getBairroCliente();
                longi = entregas.get(i).getLongitude_cliente();
                lat = entregas.get(i).getLatitude_cliente();
                vip = entregas.get(i).isVip();
                idProd = entregas.get(i).getIdProduto();
                nomeProd = entregas.get(i).getNomeProduto();
                qtdProd = entregas.get(i).getQtdProduto();
                precoProd = entregas.get(i).getPrecoProduto();
                brinde = entregas.get(i).getBrinde();
            }
        }
        
        double distancia = lat + longi;
        
        EntregaR e = new EntregaR(contEntregaRealizada, idCli, numCli, nomeCli, bairroCli, distancia, vip, idProd, nomeProd, qtdProd, precoProd, brinde);
        entregasRealizadas.add(e);
        
        EntregaRealizadaTableModel modelEntregaRealizada = new EntregaRealizadaTableModel(entregasRealizadas);
        tabelaEntregasRealizadas.setModel(modelEntregaRealizada);
        
        entregas.remove(idEntrega);
        
        EntregaTableModel modelEntrega = new EntregaTableModel(entregas);
        tabelaEntregas.setModel(modelEntrega);
        
        contEntregaRealizada++;
        
    }//GEN-LAST:event_btMarcarEntregaActionPerformed

    
    private void btSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarActionPerformed
        // TODO add your handling code here:
        
        boolean vip=true;
        
        for(int i=0; i<clientes.size(); i++){
            if(jcClientes.getSelectedItem().toString().equals(clientes.get(i).getNome().toString())){
                vip = clientes.get(i).isVip();
            }
        }
        
        if(vip){
            jtBrinde.setEditable(true);
            jtBrinde.setText("Digite o nome do brinde");
        } else{
            jtBrinde.setEditable(false);
            jtBrinde.setText("Cliente não possui brinde");
        }
        
        
    }//GEN-LAST:event_btSelecionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarCliente;
    private javax.swing.JButton btCadastrarEntrega;
    private javax.swing.JButton btCadastrarProduto;
    private javax.swing.JButton btCarregarDados;
    private javax.swing.JButton btExcluirCliente;
    private javax.swing.JButton btExcluirProduto;
    private javax.swing.JButton btMarcarEntrega;
    private javax.swing.JButton btSelecionar;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCVip;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JComboBox jcClientes;
    private javax.swing.JComboBox jcProdutos;
    private javax.swing.JTextField jtBairro;
    private javax.swing.JTextField jtBrinde;
    private javax.swing.JTextField jtLatitude;
    private javax.swing.JTextField jtLongitude;
    private javax.swing.JTextField jtNomeCliente;
    private javax.swing.JTextField jtNomeProduto;
    private javax.swing.JTextField jtNumero;
    private javax.swing.JTextField jtPrecoProduto;
    private javax.swing.JTextField jtQtdProduto;
    private javax.swing.JTextField jtRua;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JTable tabelaEntregas;
    private javax.swing.JTable tabelaEntregasRealizadas;
    private javax.swing.JTable tabelaProdutos;
    // End of variables declaration//GEN-END:variables
}